[project]
name = "python-labs"
version = "0.1.0"
description = "Лабораторные работы по Python"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.4.2",
]

[tool.mypy]
python_version = "3.9"
mypy_path = "lab_01/src"
explicit_package_bases = true
namespace_packages = true

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.pytest.ini_options]
testpaths = ["lab_01/tests"]
pythonpath = ["lab_01/src"]
